/**
 * mockData.ts — Comprehensive demo data for all portal pages.
 *
 * Used exclusively by demoAdapter.ts when VITE_DEMO_MODE=true.
 * All data is fictional. No real PHI is present.
 */

// ---------------------------------------------------------------------------
// Camps
// ---------------------------------------------------------------------------

export const CAMPS = [
  {
    id: 1,
    name: 'Camp Burnt Gin',
    location: 'Winnsboro, SC',
    description: "South Carolina's premier therapeutic overnight camp for children with special needs.",
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 2,
    name: 'Camp Burnt Gin North',
    location: 'Columbia, SC',
    description: 'Northern satellite offering day and overnight programs.',
    created_at: '2025-06-01T00:00:00Z',
    updated_at: '2025-06-01T00:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Sessions
// ---------------------------------------------------------------------------

export const SESSIONS = [
  {
    id: 1,
    camp_id: 1,
    camp: CAMPS[0],
    name: 'Summer 2026 — Session A',
    start_date: '2026-06-08',
    end_date: '2026-06-14',
    capacity: 30,
    enrolled_count: 24,
    remaining_capacity: 6,
    is_active: true,
    registration_opens_at: '2026-02-01T00:00:00Z',
    registration_closes_at: '2026-05-15T00:00:00Z',
    min_age: 7,
    max_age: 17,
    created_at: '2025-11-01T00:00:00Z',
  },
  {
    id: 2,
    camp_id: 1,
    camp: CAMPS[0],
    name: 'Summer 2026 — Session B',
    start_date: '2026-06-15',
    end_date: '2026-06-21',
    capacity: 25,
    enrolled_count: 25,
    remaining_capacity: 0,
    is_active: true,
    registration_opens_at: '2026-02-01T00:00:00Z',
    registration_closes_at: '2026-05-15T00:00:00Z',
    min_age: 7,
    max_age: 17,
    created_at: '2025-11-01T00:00:00Z',
  },
  {
    id: 3,
    camp_id: 1,
    camp: CAMPS[0],
    name: 'Summer 2026 — Session C',
    start_date: '2026-06-22',
    end_date: '2026-06-28',
    capacity: 30,
    enrolled_count: 18,
    remaining_capacity: 12,
    is_active: true,
    registration_opens_at: '2026-03-01T00:00:00Z',
    registration_closes_at: '2026-06-01T00:00:00Z',
    min_age: 7,
    max_age: 21,
    created_at: '2025-11-01T00:00:00Z',
  },
  {
    id: 4,
    camp_id: 2,
    camp: CAMPS[1],
    name: 'North Camp — Summer 2026',
    start_date: '2026-07-06',
    end_date: '2026-07-12',
    capacity: 20,
    enrolled_count: 11,
    remaining_capacity: 9,
    is_active: true,
    registration_opens_at: '2026-03-15T00:00:00Z',
    registration_closes_at: '2026-06-15T00:00:00Z',
    min_age: 8,
    max_age: 18,
    created_at: '2025-12-01T00:00:00Z',
  },
  {
    id: 5,
    camp_id: 1,
    camp: CAMPS[0],
    name: 'Fall 2026 — Session A',
    start_date: '2026-09-14',
    end_date: '2026-09-20',
    capacity: 25,
    enrolled_count: 3,
    remaining_capacity: 22,
    is_active: false,
    registration_opens_at: '2026-07-01T00:00:00Z',
    registration_closes_at: '2026-08-30T00:00:00Z',
    min_age: 7,
    max_age: 21,
    created_at: '2026-01-15T00:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Campers
// ---------------------------------------------------------------------------

export const CAMPERS = [
  {
    id: 1,
    user_id: 201,
    first_name: 'Elijah',
    last_name: 'Harmon',
    full_name: 'Elijah Harmon',
    date_of_birth: '2013-04-12',
    gender: 'male',
    tshirt_size: 'M',
    created_at: '2026-01-10T00:00:00Z',
    user: { id: 201, name: 'Patricia Harmon', email: 'pharmon@example.com' },
    applications: [{ id: 1, camp_session_id: 1, status: 'approved', session: SESSIONS[0] }],
  },
  {
    id: 2,
    user_id: 202,
    first_name: 'Maya',
    last_name: 'Chen',
    full_name: 'Maya Chen',
    date_of_birth: '2014-07-22',
    gender: 'female',
    tshirt_size: 'S',
    created_at: '2026-01-12T00:00:00Z',
    user: { id: 202, name: 'David Chen', email: 'dchen@example.com' },
    applications: [{ id: 2, camp_session_id: 1, status: 'approved', session: SESSIONS[0] }],
  },
  {
    id: 3,
    user_id: 203,
    first_name: 'Sofía',
    last_name: 'Rodriguez',
    full_name: 'Sofía Rodriguez',
    date_of_birth: '2012-11-05',
    gender: 'female',
    tshirt_size: 'L',
    created_at: '2026-01-15T00:00:00Z',
    user: { id: 203, name: 'Maria Rodriguez', email: 'mrodriguez@example.com' },
    applications: [{ id: 3, camp_session_id: 2, status: 'waitlisted', session: SESSIONS[1] }],
  },
  {
    id: 4,
    user_id: 203,
    first_name: 'Liam',
    last_name: 'Rodriguez',
    full_name: 'Liam Rodriguez',
    date_of_birth: '2015-02-28',
    gender: 'male',
    tshirt_size: 'S',
    created_at: '2026-01-15T00:00:00Z',
    user: { id: 203, name: 'Maria Rodriguez', email: 'mrodriguez@example.com' },
    applications: [{ id: 4, camp_session_id: 3, status: 'approved', session: SESSIONS[2] }],
  },
  {
    id: 5,
    user_id: 204,
    first_name: 'Ava',
    last_name: 'Thompson',
    full_name: 'Ava Thompson',
    date_of_birth: '2013-09-15',
    gender: 'female',
    tshirt_size: 'M',
    created_at: '2026-01-18T00:00:00Z',
    user: { id: 204, name: 'Kevin Thompson', email: 'kthompson@example.com' },
    applications: [{ id: 5, camp_session_id: 1, status: 'under_review', session: SESSIONS[0] }],
  },
  {
    id: 6,
    user_id: 205,
    first_name: 'Noah',
    last_name: 'Washington',
    full_name: 'Noah Washington',
    date_of_birth: '2016-03-07',
    gender: 'male',
    tshirt_size: 'XS',
    created_at: '2026-01-20T00:00:00Z',
    user: { id: 205, name: 'Lisa Washington', email: 'lwashington@example.com' },
    applications: [{ id: 6, camp_session_id: 1, status: 'submitted', session: SESSIONS[0] }],
  },
  {
    id: 7,
    user_id: 202,
    first_name: 'Isabella',
    last_name: 'Chen',
    full_name: 'Isabella Chen',
    date_of_birth: '2011-12-19',
    gender: 'female',
    tshirt_size: 'M',
    created_at: '2026-01-12T00:00:00Z',
    user: { id: 202, name: 'David Chen', email: 'dchen@example.com' },
    applications: [{ id: 7, camp_session_id: 2, status: 'approved', session: SESSIONS[1] }],
  },
  {
    id: 8,
    user_id: 206,
    first_name: 'Ethan',
    last_name: 'Taylor',
    full_name: 'Ethan Taylor',
    date_of_birth: '2014-06-30',
    gender: 'male',
    tshirt_size: 'M',
    created_at: '2026-01-22T00:00:00Z',
    user: { id: 206, name: 'Robert Taylor', email: 'rtaylor@example.com' },
    applications: [{ id: 8, camp_session_id: 1, status: 'rejected', session: SESSIONS[0] }],
  },
  {
    id: 9,
    user_id: 207,
    first_name: 'Chloe',
    last_name: 'Martin',
    full_name: 'Chloe Martin',
    date_of_birth: '2013-01-25',
    gender: 'female',
    tshirt_size: 'S',
    created_at: '2026-01-25T00:00:00Z',
    user: { id: 207, name: 'Sandra Martin', email: 'smartin@example.com' },
    applications: [{ id: 9, camp_session_id: 4, status: 'approved', session: SESSIONS[3] }],
  },
  {
    id: 10,
    user_id: 208,
    first_name: 'James',
    last_name: 'Foster',
    full_name: 'James Foster',
    date_of_birth: '2015-08-14',
    gender: 'male',
    tshirt_size: 'S',
    created_at: '2026-01-28T00:00:00Z',
    user: { id: 208, name: 'Angela Foster', email: 'afoster@example.com' },
    applications: [{ id: 10, camp_session_id: 4, status: 'approved', session: SESSIONS[3] }],
  },
  {
    id: 11,
    user_id: 209,
    first_name: 'Zoe',
    last_name: 'Patel',
    full_name: 'Zoe Patel',
    date_of_birth: '2012-05-18',
    gender: 'female',
    tshirt_size: 'M',
    created_at: '2026-02-01T00:00:00Z',
    user: { id: 209, name: 'Priya Patel', email: 'ppatel@example.com' },
    applications: [{ id: 11, camp_session_id: 3, status: 'approved', session: SESSIONS[2] }],
  },
  {
    id: 12,
    user_id: 210,
    first_name: 'Marcus',
    last_name: 'Greene',
    full_name: 'Marcus Greene',
    date_of_birth: '2014-10-03',
    gender: 'male',
    tshirt_size: 'L',
    created_at: '2026-02-03T00:00:00Z',
    user: { id: 210, name: 'Denise Greene', email: 'dgreene@example.com' },
    applications: [{ id: 12, camp_session_id: 3, status: 'submitted', session: SESSIONS[2] }],
  },
];

// ---------------------------------------------------------------------------
// Applications (flat list used by admin views)
// ---------------------------------------------------------------------------

export const APPLICATIONS = [
  {
    id: 1,
    camper_id: 1,
    camp_session_id: 1,
    status: 'approved',
    notes: 'Strong candidate. Medical team briefed.',
    submitted_at: '2026-01-11T14:22:00Z',
    reviewed_at: '2026-01-20T09:15:00Z',
    reviewer_id: 102,
    signed_at: '2026-01-11T14:25:00Z',
    signature_name: 'Patricia Harmon',
    created_at: '2026-01-11T14:00:00Z',
    camper: CAMPERS[0],
    session: SESSIONS[0],
  },
  {
    id: 2,
    camper_id: 2,
    camp_session_id: 1,
    status: 'approved',
    notes: '',
    submitted_at: '2026-01-13T10:05:00Z',
    reviewed_at: '2026-01-21T11:30:00Z',
    reviewer_id: 102,
    signed_at: '2026-01-13T10:08:00Z',
    signature_name: 'David Chen',
    created_at: '2026-01-13T10:00:00Z',
    camper: CAMPERS[1],
    session: SESSIONS[0],
  },
  {
    id: 3,
    camper_id: 3,
    camp_session_id: 2,
    status: 'waitlisted',
    notes: 'Session B is at capacity. Placed on waitlist.',
    submitted_at: '2026-01-16T16:00:00Z',
    reviewed_at: '2026-01-22T14:00:00Z',
    reviewer_id: 102,
    signed_at: '2026-01-16T16:03:00Z',
    signature_name: 'Maria Rodriguez',
    created_at: '2026-01-16T15:45:00Z',
    camper: CAMPERS[2],
    session: SESSIONS[1],
  },
  {
    id: 4,
    camper_id: 4,
    camp_session_id: 3,
    status: 'approved',
    notes: '',
    submitted_at: '2026-01-16T16:30:00Z',
    reviewed_at: '2026-01-23T10:00:00Z',
    reviewer_id: 102,
    signed_at: '2026-01-16T16:35:00Z',
    signature_name: 'Maria Rodriguez',
    created_at: '2026-01-16T16:00:00Z',
    camper: CAMPERS[3],
    session: SESSIONS[2],
  },
  {
    id: 5,
    camper_id: 5,
    camp_session_id: 1,
    status: 'under_review',
    notes: 'Awaiting additional medical clearance documentation.',
    submitted_at: '2026-01-19T09:00:00Z',
    reviewed_at: null,
    reviewer_id: null,
    signed_at: '2026-01-19T09:02:00Z',
    signature_name: 'Kevin Thompson',
    created_at: '2026-01-18T20:00:00Z',
    camper: CAMPERS[4],
    session: SESSIONS[0],
  },
  {
    id: 6,
    camper_id: 6,
    camp_session_id: 1,
    status: 'submitted',
    notes: '',
    submitted_at: '2026-01-21T12:00:00Z',
    reviewed_at: null,
    reviewer_id: null,
    signed_at: '2026-01-21T12:02:00Z',
    signature_name: 'Lisa Washington',
    created_at: '2026-01-20T18:00:00Z',
    camper: CAMPERS[5],
    session: SESSIONS[0],
  },
  {
    id: 7,
    camper_id: 7,
    camp_session_id: 2,
    status: 'approved',
    notes: '',
    submitted_at: '2026-01-13T11:00:00Z',
    reviewed_at: '2026-01-21T12:00:00Z',
    reviewer_id: 9999,
    signed_at: '2026-01-13T11:05:00Z',
    signature_name: 'David Chen',
    created_at: '2026-01-13T10:30:00Z',
    camper: CAMPERS[6],
    session: SESSIONS[1],
  },
  {
    id: 8,
    camper_id: 8,
    camp_session_id: 1,
    status: 'rejected',
    notes: 'Unable to accommodate required medical support at this time.',
    submitted_at: '2026-01-23T08:00:00Z',
    reviewed_at: '2026-01-28T14:00:00Z',
    reviewer_id: 102,
    signed_at: '2026-01-23T08:05:00Z',
    signature_name: 'Robert Taylor',
    created_at: '2026-01-22T19:00:00Z',
    camper: CAMPERS[7],
    session: SESSIONS[0],
  },
  {
    id: 9,
    camper_id: 9,
    camp_session_id: 4,
    status: 'approved',
    notes: '',
    submitted_at: '2026-01-26T14:00:00Z',
    reviewed_at: '2026-02-05T10:00:00Z',
    reviewer_id: 9999,
    signed_at: '2026-01-26T14:03:00Z',
    signature_name: 'Sandra Martin',
    created_at: '2026-01-25T20:00:00Z',
    camper: CAMPERS[8],
    session: SESSIONS[3],
  },
  {
    id: 10,
    camper_id: 10,
    camp_session_id: 4,
    status: 'approved',
    notes: '',
    submitted_at: '2026-01-29T09:00:00Z',
    reviewed_at: '2026-02-06T11:00:00Z',
    reviewer_id: 9999,
    signed_at: '2026-01-29T09:02:00Z',
    signature_name: 'Angela Foster',
    created_at: '2026-01-28T18:00:00Z',
    camper: CAMPERS[9],
    session: SESSIONS[3],
  },
  {
    id: 11,
    camper_id: 11,
    camp_session_id: 3,
    status: 'approved',
    notes: '',
    submitted_at: '2026-02-02T10:00:00Z',
    reviewed_at: '2026-02-10T09:00:00Z',
    reviewer_id: 102,
    signed_at: '2026-02-02T10:05:00Z',
    signature_name: 'Priya Patel',
    created_at: '2026-02-01T18:00:00Z',
    camper: CAMPERS[10],
    session: SESSIONS[2],
  },
  {
    id: 12,
    camper_id: 12,
    camp_session_id: 3,
    status: 'submitted',
    notes: '',
    submitted_at: '2026-02-04T14:00:00Z',
    reviewed_at: null,
    reviewer_id: null,
    signed_at: '2026-02-04T14:02:00Z',
    signature_name: 'Denise Greene',
    created_at: '2026-02-03T20:00:00Z',
    camper: CAMPERS[11],
    session: SESSIONS[2],
  },
];

// ---------------------------------------------------------------------------
// System users (admin staff)
// ---------------------------------------------------------------------------

export const ADMIN_USERS = [
  {
    id: 9999,
    name: 'Demo Admin',
    email: 'demo@campburntgin.dev',
    role: 'admin',
    email_verified_at: '2026-01-01T00:00:00Z',
    mfa_enabled: false,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 101,
    name: 'Sarah Mitchell',
    email: 'smitchell@campburntgin.org',
    role: 'super_admin',
    email_verified_at: '2025-09-01T00:00:00Z',
    mfa_enabled: true,
    created_at: '2025-09-01T00:00:00Z',
  },
  {
    id: 102,
    name: 'James Whitaker',
    email: 'jwhitaker@campburntgin.org',
    role: 'admin',
    email_verified_at: '2025-09-01T00:00:00Z',
    mfa_enabled: false,
    created_at: '2025-09-01T00:00:00Z',
  },
  {
    id: 103,
    name: 'Dr. Patricia Chen',
    email: 'pchen@campburntgin.org',
    role: 'medical',
    email_verified_at: '2025-09-01T00:00:00Z',
    mfa_enabled: true,
    created_at: '2025-09-01T00:00:00Z',
  },
  {
    id: 104,
    name: 'Robert Taylor',
    email: 'rtaylor@campburntgin.org',
    role: 'admin',
    email_verified_at: '2025-10-01T00:00:00Z',
    mfa_enabled: false,
    created_at: '2025-10-01T00:00:00Z',
  },
  {
    id: 201,
    name: 'Patricia Harmon',
    email: 'pharmon@example.com',
    role: 'applicant',
    email_verified_at: '2026-01-10T00:00:00Z',
    mfa_enabled: false,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 202,
    name: 'David Chen',
    email: 'dchen@example.com',
    role: 'applicant',
    email_verified_at: '2026-01-12T00:00:00Z',
    mfa_enabled: false,
    created_at: '2026-01-12T00:00:00Z',
  },
  {
    id: 203,
    name: 'Maria Rodriguez',
    email: 'mrodriguez@example.com',
    role: 'applicant',
    email_verified_at: '2026-01-15T00:00:00Z',
    mfa_enabled: false,
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 204,
    name: 'Kevin Thompson',
    email: 'kthompson@example.com',
    role: 'applicant',
    email_verified_at: '2026-01-18T00:00:00Z',
    mfa_enabled: false,
    created_at: '2026-01-18T00:00:00Z',
  },
  {
    id: 205,
    name: 'Lisa Washington',
    email: 'lwashington@example.com',
    role: 'applicant',
    email_verified_at: '2026-01-20T00:00:00Z',
    mfa_enabled: false,
    created_at: '2026-01-20T00:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Conversations / Inbox
// ---------------------------------------------------------------------------

const ADMIN_PARTICIPANT = { id: 9999, name: 'Demo Admin', email: 'demo@campburntgin.dev', role: 'admin' };

export const CONVERSATIONS = [
  {
    id: 1,
    subject: 'Session A — Medical Form Follow-Up',
    category: 'medical',
    created_by_id: 9999,
    participants: [
      ADMIN_PARTICIPANT,
      { id: 201, name: 'Patricia Harmon', email: 'pharmon@example.com', role: 'applicant' },
    ],
    last_message: {
      id: 3,
      conversation_id: 1,
      sender_id: 201,
      sender: { id: 201, name: 'Patricia Harmon', email: 'pharmon@example.com', role: 'applicant' },
      body: "I've uploaded the completed health form. Please let me know if anything is missing.",
      read_at: null,
      created_at: '2026-03-18T14:30:00Z',
    },
    unread_count: 1,
    is_starred: false,
    is_important: true,
    is_trashed: false,
    is_system_generated: false,
    created_at: '2026-03-15T09:00:00Z',
    updated_at: '2026-03-18T14:30:00Z',
  },
  {
    id: 2,
    subject: 'Question about Session B waitlist',
    category: 'application',
    created_by_id: 203,
    participants: [
      ADMIN_PARTICIPANT,
      { id: 203, name: 'Maria Rodriguez', email: 'mrodriguez@example.com', role: 'applicant' },
    ],
    last_message: {
      id: 5,
      conversation_id: 2,
      sender_id: 9999,
      sender: ADMIN_PARTICIPANT,
      body: "Hi Maria, Sofía is currently #3 on the waitlist for Session B. We'll notify you as soon as a spot opens.",
      read_at: '2026-03-17T10:00:00Z',
      created_at: '2026-03-17T09:45:00Z',
    },
    unread_count: 0,
    is_starred: true,
    is_important: false,
    is_trashed: false,
    is_system_generated: false,
    created_at: '2026-03-16T11:00:00Z',
    updated_at: '2026-03-17T09:45:00Z',
  },
  {
    id: 3,
    subject: 'Staff Briefing — Session Schedules',
    category: 'general',
    created_by_id: 101,
    participants: [
      ADMIN_PARTICIPANT,
      { id: 101, name: 'Sarah Mitchell', email: 'smitchell@campburntgin.org', role: 'super_admin' },
      { id: 102, name: 'James Whitaker', email: 'jwhitaker@campburntgin.org', role: 'admin' },
    ],
    last_message: {
      id: 8,
      conversation_id: 3,
      sender_id: 101,
      sender: { id: 101, name: 'Sarah Mitchell', email: 'smitchell@campburntgin.org', role: 'super_admin' },
      body: 'Updated schedule attached. All session leads please review before April 1.',
      read_at: '2026-03-19T08:00:00Z',
      created_at: '2026-03-18T16:00:00Z',
    },
    unread_count: 0,
    is_starred: false,
    is_important: false,
    is_trashed: false,
    is_system_generated: false,
    created_at: '2026-03-18T15:00:00Z',
    updated_at: '2026-03-18T16:00:00Z',
  },
  {
    id: 4,
    subject: null,
    category: 'application',
    created_by_id: null,
    participants: [ADMIN_PARTICIPANT],
    last_message: {
      id: 10,
      conversation_id: 4,
      sender_id: null,
      sender: null,
      body: "Application #5 (Ava Thompson) has been moved to 'Under Review'. Additional medical clearance has been requested.",
      read_at: '2026-03-19T09:00:00Z',
      created_at: '2026-03-19T08:55:00Z',
    },
    unread_count: 0,
    is_starred: false,
    is_important: false,
    is_trashed: false,
    is_system_generated: true,
    system_event_type: 'application.status_changed',
    system_event_category: 'application',
    related_entity_type: 'Application',
    related_entity_id: 5,
    created_at: '2026-03-19T08:55:00Z',
    updated_at: '2026-03-19T08:55:00Z',
  },
  {
    id: 5,
    subject: "Ava Thompson's medical clearance",
    category: 'medical',
    created_by_id: 103,
    participants: [
      ADMIN_PARTICIPANT,
      { id: 103, name: 'Dr. Patricia Chen', email: 'pchen@campburntgin.org', role: 'medical' },
    ],
    last_message: {
      id: 12,
      conversation_id: 5,
      sender_id: 103,
      sender: { id: 103, name: 'Dr. Patricia Chen', email: 'pchen@campburntgin.org', role: 'medical' },
      body: "I've reviewed Ava's file. We need the updated neurologist report before I can sign off. Can you request it from the family?",
      read_at: null,
      created_at: '2026-03-20T07:30:00Z',
    },
    unread_count: 1,
    is_starred: false,
    is_important: true,
    is_trashed: false,
    is_system_generated: false,
    created_at: '2026-03-19T15:00:00Z',
    updated_at: '2026-03-20T07:30:00Z',
  },
];

export const MESSAGES: Record<number, object[]> = {
  1: [
    {
      id: 1,
      conversation_id: 1,
      sender_id: 9999,
      sender: ADMIN_PARTICIPANT,
      body: "Hi Patricia, we noticed the health form for Elijah hasn't been completed yet. The deadline is April 15. Please upload it through your applicant portal.",
      read_at: '2026-03-16T10:00:00Z',
      created_at: '2026-03-15T09:00:00Z',
    },
    {
      id: 2,
      conversation_id: 1,
      sender_id: 201,
      sender: { id: 201, name: 'Patricia Harmon', email: 'pharmon@example.com', role: 'applicant' },
      body: 'Thank you for the reminder! I will get it uploaded this week.',
      read_at: '2026-03-16T10:05:00Z',
      created_at: '2026-03-16T09:00:00Z',
    },
    {
      id: 3,
      conversation_id: 1,
      sender_id: 201,
      sender: { id: 201, name: 'Patricia Harmon', email: 'pharmon@example.com', role: 'applicant' },
      body: "I've uploaded the completed health form. Please let me know if anything is missing.",
      read_at: null,
      created_at: '2026-03-18T14:30:00Z',
    },
  ],
  2: [
    {
      id: 4,
      conversation_id: 2,
      sender_id: 203,
      sender: { id: 203, name: 'Maria Rodriguez', email: 'mrodriguez@example.com', role: 'applicant' },
      body: 'Hello, my daughter Sofía is on the waitlist for Session B. Is there any idea when a spot might open?',
      read_at: '2026-03-17T09:44:00Z',
      created_at: '2026-03-16T11:00:00Z',
    },
    {
      id: 5,
      conversation_id: 2,
      sender_id: 9999,
      sender: ADMIN_PARTICIPANT,
      body: "Hi Maria, Sofía is currently #3 on the waitlist for Session B. We'll notify you as soon as a spot opens.",
      read_at: '2026-03-17T10:00:00Z',
      created_at: '2026-03-17T09:45:00Z',
    },
  ],
  3: [
    {
      id: 6,
      conversation_id: 3,
      sender_id: 101,
      sender: { id: 101, name: 'Sarah Mitchell', email: 'smitchell@campburntgin.org', role: 'super_admin' },
      body: 'Team — please review the attached session schedules for Summer 2026.',
      read_at: '2026-03-18T15:30:00Z',
      created_at: '2026-03-18T15:00:00Z',
    },
    {
      id: 7,
      conversation_id: 3,
      sender_id: 9999,
      sender: ADMIN_PARTICIPANT,
      body: 'Got it, reviewing now.',
      read_at: '2026-03-18T15:45:00Z',
      created_at: '2026-03-18T15:40:00Z',
    },
    {
      id: 8,
      conversation_id: 3,
      sender_id: 101,
      sender: { id: 101, name: 'Sarah Mitchell', email: 'smitchell@campburntgin.org', role: 'super_admin' },
      body: 'Updated schedule attached. All session leads please review before April 1.',
      read_at: '2026-03-19T08:00:00Z',
      created_at: '2026-03-18T16:00:00Z',
    },
  ],
  4: [
    {
      id: 10,
      conversation_id: 4,
      sender_id: null,
      sender: null,
      body: "Application #5 (Ava Thompson) has been moved to 'Under Review'. Additional medical clearance has been requested.",
      read_at: '2026-03-19T09:00:00Z',
      created_at: '2026-03-19T08:55:00Z',
    },
  ],
  5: [
    {
      id: 11,
      conversation_id: 5,
      sender_id: 9999,
      sender: ADMIN_PARTICIPANT,
      body: 'Dr. Chen, can you review Ava Thompson\'s application file? She\'s pending medical clearance for Session A.',
      read_at: '2026-03-19T15:30:00Z',
      created_at: '2026-03-19T15:00:00Z',
    },
    {
      id: 12,
      conversation_id: 5,
      sender_id: 103,
      sender: { id: 103, name: 'Dr. Patricia Chen', email: 'pchen@campburntgin.org', role: 'medical' },
      body: "I've reviewed Ava's file. We need the updated neurologist report before I can sign off. Can you request it from the family?",
      read_at: null,
      created_at: '2026-03-20T07:30:00Z',
    },
  ],
};

// ---------------------------------------------------------------------------
// Announcements
// ---------------------------------------------------------------------------

export const ANNOUNCEMENTS = [
  {
    id: 1,
    author_id: 101,
    author: { id: 101, name: 'Sarah Mitchell' },
    title: 'Welcome to Camp Burnt Gin 2026 Season!',
    body: "We're thrilled to announce that registration for Summer 2026 is now open. Sessions A, B, and C will run throughout June, with the North Camp session in July. Our team is working hard to make this our best season yet. Stay tuned for important dates and updates.",
    is_pinned: true,
    is_urgent: false,
    audience: 'all',
    target_session_id: null,
    published_at: '2026-02-01T09:00:00Z',
    created_at: '2026-02-01T08:00:00Z',
    updated_at: '2026-02-01T08:00:00Z',
  },
  {
    id: 2,
    author_id: 9999,
    author: { id: 9999, name: 'Demo Admin' },
    title: 'Health Forms Due April 15 — Session A & B Families',
    body: "All families with approved applications for Session A and Session B must submit completed health forms by April 15. Forms can be uploaded through your applicant portal. Contact us if you need assistance. Incomplete forms may result in your application being placed on hold.",
    is_pinned: false,
    is_urgent: true,
    audience: 'accepted',
    target_session_id: null,
    published_at: '2026-03-01T09:00:00Z',
    created_at: '2026-03-01T08:00:00Z',
    updated_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 3,
    author_id: 101,
    author: { id: 101, name: 'Sarah Mitchell' },
    title: 'Staff Orientation — May 30–31',
    body: 'All Camp Burnt Gin staff are required to attend the annual orientation on May 30–31 at the main camp facility. Agenda, accommodation details, and training materials will be distributed via staff portal. Please confirm attendance by April 30.',
    is_pinned: false,
    is_urgent: false,
    audience: 'staff',
    target_session_id: null,
    published_at: '2026-03-05T10:00:00Z',
    created_at: '2026-03-05T09:00:00Z',
    updated_at: '2026-03-05T09:00:00Z',
  },
  {
    id: 4,
    author_id: 102,
    author: { id: 102, name: 'James Whitaker' },
    title: 'Session A — Packing List Now Available',
    body: "The recommended packing list for Session A is now available in your applicant portal under 'Resources'. Please review carefully — some items are required for program participation. Electric wheelchairs and mobility devices must be reported to the medical team in advance.",
    is_pinned: false,
    is_urgent: false,
    audience: 'session',
    target_session_id: 1,
    published_at: '2026-03-10T09:00:00Z',
    created_at: '2026-03-10T08:00:00Z',
    updated_at: '2026-03-10T08:00:00Z',
  },
  {
    id: 5,
    author_id: 9999,
    author: { id: 9999, name: 'Demo Admin' },
    title: 'Fall 2026 Registration Opens July 1',
    body: "Fall Session A registration will open July 1, 2026. Families of returning campers will receive priority access starting June 25. Capacity is limited to 25 participants. Applications will be accepted on a rolling basis.",
    is_pinned: false,
    is_urgent: false,
    audience: 'all',
    target_session_id: null,
    published_at: '2026-03-15T09:00:00Z',
    created_at: '2026-03-15T08:00:00Z',
    updated_at: '2026-03-15T08:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Calendar events
// ---------------------------------------------------------------------------

export const CALENDAR_EVENTS = [
  {
    id: 1,
    created_by: 101,
    creator: { id: 101, name: 'Sarah Mitchell' },
    title: 'Health Form Deadline — Sessions A & B',
    description: 'All families with approved applications for Session A and B must submit health forms.',
    event_type: 'deadline',
    color: '#ef4444',
    starts_at: '2026-04-15T23:59:00Z',
    ends_at: null,
    all_day: true,
    audience: 'accepted',
    target_session_id: null,
    created_at: '2026-02-15T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 2,
    created_by: 101,
    creator: { id: 101, name: 'Sarah Mitchell' },
    title: 'Staff Orientation',
    description: 'Annual staff training and orientation at main camp facility.',
    event_type: 'orientation',
    color: '#8b5cf6',
    starts_at: '2026-05-30T08:00:00Z',
    ends_at: '2026-05-31T17:00:00Z',
    all_day: false,
    audience: 'staff',
    target_session_id: null,
    created_at: '2026-02-20T00:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 3,
    created_by: 101,
    creator: { id: 101, name: 'Sarah Mitchell' },
    title: 'Session A Begins',
    description: 'Summer 2026 Session A — camper arrival day.',
    event_type: 'session',
    color: '#16a34a',
    starts_at: '2026-06-08T10:00:00Z',
    ends_at: '2026-06-14T14:00:00Z',
    all_day: false,
    audience: 'all',
    target_session_id: 1,
    created_at: '2025-11-01T00:00:00Z',
    updated_at: '2025-11-01T00:00:00Z',
  },
  {
    id: 4,
    created_by: 101,
    creator: { id: 101, name: 'Sarah Mitchell' },
    title: 'Session B Begins',
    description: 'Summer 2026 Session B — camper arrival day.',
    event_type: 'session',
    color: '#16a34a',
    starts_at: '2026-06-15T10:00:00Z',
    ends_at: '2026-06-21T14:00:00Z',
    all_day: false,
    audience: 'all',
    target_session_id: 2,
    created_at: '2025-11-01T00:00:00Z',
    updated_at: '2025-11-01T00:00:00Z',
  },
  {
    id: 5,
    created_by: 101,
    creator: { id: 101, name: 'Sarah Mitchell' },
    title: 'Session C Begins',
    description: 'Summer 2026 Session C — camper arrival day.',
    event_type: 'session',
    color: '#16a34a',
    starts_at: '2026-06-22T10:00:00Z',
    ends_at: '2026-06-28T14:00:00Z',
    all_day: false,
    audience: 'all',
    target_session_id: 3,
    created_at: '2025-11-01T00:00:00Z',
    updated_at: '2025-11-01T00:00:00Z',
  },
  {
    id: 6,
    created_by: 101,
    creator: { id: 101, name: 'Sarah Mitchell' },
    title: 'North Camp Session Begins',
    description: 'North Camp Summer 2026 — camper arrival day.',
    event_type: 'session',
    color: '#0ea5e9',
    starts_at: '2026-07-06T10:00:00Z',
    ends_at: '2026-07-12T14:00:00Z',
    all_day: false,
    audience: 'all',
    target_session_id: 4,
    created_at: '2025-12-01T00:00:00Z',
    updated_at: '2025-12-01T00:00:00Z',
  },
  {
    id: 7,
    created_by: 9999,
    creator: { id: 9999, name: 'Demo Admin' },
    title: 'Registration Closes — Sessions A & B',
    description: 'Final deadline to submit applications for Sessions A and B.',
    event_type: 'deadline',
    color: '#f97316',
    starts_at: '2026-05-15T23:59:00Z',
    ends_at: null,
    all_day: true,
    audience: 'all',
    target_session_id: null,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-01-10T00:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

export const NOTIFICATIONS = [
  {
    id: 'notif-1',
    type: 'application_status_changed',
    title: 'Application Status Updated',
    message: "Elijah Harmon's application has been approved for Session A.",
    read_at: '2026-03-20T08:00:00Z',
    created_at: '2026-01-20T09:15:00Z',
    data: { application_id: 1 },
  },
  {
    id: 'notif-2',
    type: 'new_message',
    title: 'New Message from Dr. Patricia Chen',
    message: "Regarding Ava Thompson's medical clearance — neurologist report needed.",
    read_at: null,
    created_at: '2026-03-20T07:30:00Z',
    data: { conversation_id: 5 },
  },
  {
    id: 'notif-3',
    type: 'new_message',
    title: 'New Message from Patricia Harmon',
    message: "Health form uploaded for Elijah. Please confirm receipt.",
    read_at: null,
    created_at: '2026-03-18T14:30:00Z',
    data: { conversation_id: 1 },
  },
  {
    id: 'notif-4',
    type: 'application_submitted',
    title: 'New Application Received',
    message: 'Marcus Greene submitted an application for Session C.',
    read_at: '2026-03-20T08:00:00Z',
    created_at: '2026-02-04T14:00:00Z',
    data: { application_id: 12 },
  },
  {
    id: 'notif-5',
    type: 'deadline_reminder',
    title: 'Health Form Deadline Approaching',
    message: 'Health forms for Session A & B are due in 26 days.',
    read_at: null,
    created_at: '2026-03-20T06:00:00Z',
    data: {},
  },
];

// ---------------------------------------------------------------------------
// Document requests
// ---------------------------------------------------------------------------

export const DOCUMENT_REQUESTS = [
  {
    id: 1,
    applicant_id: 204,
    applicant_name: 'Kevin Thompson',
    application_id: 5,
    camper_id: 5,
    camper_name: 'Ava Thompson',
    requested_by_admin_id: 9999,
    requested_by_name: 'Demo Admin',
    document_type: 'Neurologist Report',
    instructions: 'Please upload the most recent neurologist report (within 12 months) for Ava.',
    status: 'awaiting_upload',
    due_date: '2026-04-01',
    uploaded_file_name: null,
    uploaded_at: null,
    rejection_reason: null,
    reviewed_at: null,
    reviewed_by_name: null,
    download_url: null,
    created_at: '2026-03-19T09:00:00Z',
  },
  {
    id: 2,
    applicant_id: 201,
    applicant_name: 'Patricia Harmon',
    application_id: 1,
    camper_id: 1,
    camper_name: 'Elijah Harmon',
    requested_by_admin_id: 9999,
    requested_by_name: 'Demo Admin',
    document_type: 'Annual Health Form',
    instructions: 'Please complete and upload the 2026 Annual Health Form.',
    status: 'uploaded',
    due_date: '2026-04-15',
    uploaded_file_name: 'elijah_health_form_2026.pdf',
    uploaded_at: '2026-03-18T14:30:00Z',
    rejection_reason: null,
    reviewed_at: null,
    reviewed_by_name: null,
    download_url: null,
    created_at: '2026-03-15T09:00:00Z',
  },
  {
    id: 3,
    applicant_id: 202,
    applicant_name: 'David Chen',
    application_id: 7,
    camper_id: 7,
    camper_name: 'Isabella Chen',
    requested_by_admin_id: 102,
    requested_by_name: 'James Whitaker',
    document_type: 'Insurance Card',
    instructions: 'Please upload a copy of your insurance card (front and back).',
    status: 'approved',
    due_date: '2026-03-30',
    uploaded_file_name: 'chen_insurance_card.pdf',
    uploaded_at: '2026-03-12T10:00:00Z',
    rejection_reason: null,
    reviewed_at: '2026-03-14T11:00:00Z',
    reviewed_by_name: 'James Whitaker',
    download_url: null,
    created_at: '2026-03-08T09:00:00Z',
  },
];

export const DOCUMENT_REQUEST_STATS = {
  total: 3,
  awaiting_upload: 1,
  uploaded: 1,
  under_review: 0,
  approved: 1,
  rejected: 0,
  overdue: 0,
};

// ---------------------------------------------------------------------------
// Reports summary
// ---------------------------------------------------------------------------

export const REPORTS_SUMMARY = {
  total_campers: 12,
  total_applications: 12,
  accepted_applications: 7,
  pending_applications: 3,
  rejected_applications: 1,
  applications_by_status: {
    approved: 7,
    pending: 3,
    under_review: 1,
    rejected: 1,
    waitlisted: 1,
    cancelled: 0,
    withdrawn: 0,
    draft: 0,
  },
  sessions: [
    { id: 1, name: 'Summer 2026 — Session A', capacity: 30, enrolled: 24 },
    { id: 2, name: 'Summer 2026 — Session B', capacity: 25, enrolled: 25 },
    { id: 3, name: 'Summer 2026 — Session C', capacity: 30, enrolled: 18 },
    { id: 4, name: 'North Camp — Summer 2026', capacity: 20, enrolled: 11 },
  ],
  applications_over_time: [
    { month: 'Nov 2025', count: 0 },
    { month: 'Dec 2025', count: 1 },
    { month: 'Jan 2026', count: 8 },
    { month: 'Feb 2026', count: 3 },
    { month: 'Mar 2026', count: 0 },
  ],
};

// ---------------------------------------------------------------------------
// Audit log
// ---------------------------------------------------------------------------

export const AUDIT_LOG_ENTRIES = [
  {
    id: 1,
    request_id: 'req-aaa',
    user_id: 9999,
    user: { id: 9999, name: 'Demo Admin', email: 'demo@campburntgin.dev' },
    event_type: 'update',
    category: 'Application',
    action: 'application.status_changed',
    description: null,
    human_description: "Demo Admin changed Application #1 status to 'approved'.",
    auditable_type: 'Application',
    auditable_id: 1,
    entity_label: 'Application #1 — Elijah Harmon',
    old_values: { status: 'under_review' },
    new_values: { status: 'approved' },
    metadata: null,
    ip_address: '127.0.0.1',
    user_agent: 'Mozilla/5.0',
    created_at: '2026-01-20T09:15:00Z',
  },
  {
    id: 2,
    request_id: 'req-bbb',
    user_id: 102,
    user: { id: 102, name: 'James Whitaker', email: 'jwhitaker@campburntgin.org' },
    event_type: 'update',
    category: 'Application',
    action: 'application.status_changed',
    description: null,
    human_description: "James Whitaker changed Application #2 status to 'approved'.",
    auditable_type: 'Application',
    auditable_id: 2,
    entity_label: 'Application #2 — Maya Chen',
    old_values: { status: 'submitted' },
    new_values: { status: 'approved' },
    metadata: null,
    ip_address: '127.0.0.1',
    user_agent: 'Mozilla/5.0',
    created_at: '2026-01-21T11:30:00Z',
  },
  {
    id: 3,
    request_id: 'req-ccc',
    user_id: 9999,
    user: { id: 9999, name: 'Demo Admin', email: 'demo@campburntgin.dev' },
    event_type: 'create',
    category: 'Session',
    action: 'session.created',
    description: null,
    human_description: "Demo Admin created session 'Fall 2026 — Session A'.",
    auditable_type: 'CampSession',
    auditable_id: 5,
    entity_label: 'Fall 2026 — Session A',
    old_values: null,
    new_values: { name: 'Fall 2026 — Session A', capacity: 25 },
    metadata: null,
    ip_address: '127.0.0.1',
    user_agent: 'Mozilla/5.0',
    created_at: '2026-01-15T14:00:00Z',
  },
  {
    id: 4,
    request_id: 'req-ddd',
    user_id: 101,
    user: { id: 101, name: 'Sarah Mitchell', email: 'smitchell@campburntgin.org' },
    event_type: 'update',
    category: 'User',
    action: 'user.role_changed',
    description: null,
    human_description: "Sarah Mitchell changed Robert Taylor's role to 'admin'.",
    auditable_type: 'User',
    auditable_id: 104,
    entity_label: 'Robert Taylor',
    old_values: { role: 'applicant' },
    new_values: { role: 'admin' },
    metadata: null,
    ip_address: '127.0.0.1',
    user_agent: 'Mozilla/5.0',
    created_at: '2025-10-01T09:00:00Z',
  },
  {
    id: 5,
    request_id: 'req-eee',
    user_id: 9999,
    user: { id: 9999, name: 'Demo Admin', email: 'demo@campburntgin.dev' },
    event_type: 'create',
    category: 'Document',
    action: 'document_request.created',
    description: null,
    human_description: "Demo Admin created a document request for Kevin Thompson (Ava Thompson — Neurologist Report).",
    auditable_type: 'DocumentRequest',
    auditable_id: 1,
    entity_label: 'Document Request #1',
    old_values: null,
    new_values: { document_type: 'Neurologist Report', applicant: 'Kevin Thompson' },
    metadata: null,
    ip_address: '127.0.0.1',
    user_agent: 'Mozilla/5.0',
    created_at: '2026-03-19T09:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Medical data (for camper detail / medical portal)
// ---------------------------------------------------------------------------

export const MEDICAL_RECORDS: Record<number, object> = {
  1: {
    id: 1,
    camper_id: 1,
    primary_diagnosis: 'Cerebral Palsy (Spastic Diplegia)',
    physician_name: 'Dr. William Harris',
    physician_phone: '803-555-0101',
    insurance_provider: 'BlueCross BlueShield SC',
    insurance_policy_number: 'BCB-2026-88123',
    special_needs: 'Uses a manual wheelchair. Requires transfer assistance for all activities.',
    dietary_restrictions: 'No dairy (lactose intolerant). Pureed texture for some foods.',
    notes: 'Elijah is a friendly and motivated camper. Engages well with peer activities.',
    has_seizures: false,
    last_seizure_date: null,
    seizure_description: null,
    has_neurostimulator: false,
    allergies: [
      { id: 1, name: 'Penicillin', severity: 'severe', reaction: 'Hives and breathing difficulty', treatment: 'Epinephrine auto-injector' },
    ],
    medications: [
      { id: 1, name: 'Baclofen', dosage: '10mg', frequency: 'Twice daily', route: 'oral', purpose: 'Muscle spasticity', notes: 'Take with food' },
    ],
    diagnoses: [
      { id: 1, name: 'Cerebral Palsy', icd_code: 'G80.1', notes: 'Spastic diplegia affecting lower extremities' },
    ],
  },
  5: {
    id: 5,
    camper_id: 5,
    primary_diagnosis: 'Autism Spectrum Disorder (Level 2)',
    physician_name: 'Dr. Amanda Fischer',
    physician_phone: '803-555-0205',
    insurance_provider: 'Aetna',
    insurance_policy_number: 'AET-2026-44571',
    special_needs: 'Sensory sensitivities — avoid loud environments where possible. AAC device user.',
    dietary_restrictions: 'Strict gluten-free diet.',
    notes: 'Neurologist report pending (required for clearance).',
    has_seizures: false,
    last_seizure_date: null,
    seizure_description: null,
    has_neurostimulator: false,
    allergies: [],
    medications: [
      { id: 5, name: 'Aripiprazole', dosage: '5mg', frequency: 'Once daily', route: 'oral', purpose: 'Behavioral regulation', notes: 'Morning administration preferred' },
    ],
    diagnoses: [
      { id: 5, name: 'Autism Spectrum Disorder', icd_code: 'F84.0', notes: 'Level 2 severity' },
    ],
  },
};

export const CAMPER_RISK_SUMMARIES: Record<number, object> = {
  1: {
    risk_level: 'medium',
    flags: ['allergy:severe', 'mobility:wheelchair'],
    allergies_count: 1,
    medications_count: 1,
    has_severe_allergy: true,
    requires_mobility_assistance: true,
  },
  5: {
    risk_level: 'high',
    flags: ['pending_clearance', 'dietary:gluten_free'],
    allergies_count: 0,
    medications_count: 1,
    has_severe_allergy: false,
    requires_mobility_assistance: false,
  },
};

// ---------------------------------------------------------------------------
// Session dashboard
// ---------------------------------------------------------------------------

export const SESSION_DASHBOARDS: Record<number, object> = {
  1: {
    session: { id: 1, name: 'Summer 2026 — Session A', camp: 'Camp Burnt Gin', start_date: '2026-06-08', end_date: '2026-06-14', is_active: true },
    capacity_stats: { capacity: 30, enrolled: 24, remaining: 6, fill_pct: 80, is_at_capacity: false },
    application_stats: { total_submitted: 6, pending: 1, under_review: 1, approved: 3, rejected: 1, waitlisted: 0, cancelled: 0, acceptance_rate: 60 },
    recent_applications: [
      { id: 6, camper_name: 'Noah Washington', status: 'submitted', submitted_at: '2026-01-21T12:00:00Z' },
      { id: 5, camper_name: 'Ava Thompson', status: 'under_review', submitted_at: '2026-01-19T09:00:00Z' },
      { id: 8, camper_name: 'Ethan Taylor', status: 'rejected', submitted_at: '2026-01-23T08:00:00Z' },
      { id: 2, camper_name: 'Maya Chen', status: 'approved', submitted_at: '2026-01-13T10:05:00Z' },
      { id: 1, camper_name: 'Elijah Harmon', status: 'approved', submitted_at: '2026-01-11T14:22:00Z' },
    ],
    age_distribution: { '7-9': 1, '10-12': 2, '13-15': 3, '16-17': 0 },
    gender_distribution: { male: 3, female: 3 },
  },
  2: {
    session: { id: 2, name: 'Summer 2026 — Session B', camp: 'Camp Burnt Gin', start_date: '2026-06-15', end_date: '2026-06-21', is_active: true },
    capacity_stats: { capacity: 25, enrolled: 25, remaining: 0, fill_pct: 100, is_at_capacity: true },
    application_stats: { total_submitted: 3, pending: 0, under_review: 0, approved: 2, rejected: 0, waitlisted: 1, cancelled: 0, acceptance_rate: 67 },
    recent_applications: [
      { id: 3, camper_name: 'Sofía Rodriguez', status: 'waitlisted', submitted_at: '2026-01-16T16:00:00Z' },
      { id: 7, camper_name: 'Isabella Chen', status: 'approved', submitted_at: '2026-01-13T11:00:00Z' },
    ],
    age_distribution: { '7-9': 0, '10-12': 1, '13-15': 1, '16-17': 0 },
    gender_distribution: { male: 0, female: 2 },
  },
  3: {
    session: { id: 3, name: 'Summer 2026 — Session C', camp: 'Camp Burnt Gin', start_date: '2026-06-22', end_date: '2026-06-28', is_active: true },
    capacity_stats: { capacity: 30, enrolled: 18, remaining: 12, fill_pct: 60, is_at_capacity: false },
    application_stats: { total_submitted: 3, pending: 1, under_review: 0, approved: 2, rejected: 0, waitlisted: 0, cancelled: 0, acceptance_rate: 67 },
    recent_applications: [
      { id: 12, camper_name: 'Marcus Greene', status: 'submitted', submitted_at: '2026-02-04T14:00:00Z' },
      { id: 11, camper_name: 'Zoe Patel', status: 'approved', submitted_at: '2026-02-02T10:00:00Z' },
      { id: 4, camper_name: 'Liam Rodriguez', status: 'approved', submitted_at: '2026-01-16T16:30:00Z' },
    ],
    age_distribution: { '7-9': 0, '10-12': 1, '13-15': 2, '16-17': 0 },
    gender_distribution: { male: 1, female: 2 },
  },
  4: {
    session: { id: 4, name: 'North Camp — Summer 2026', camp: 'Camp Burnt Gin North', start_date: '2026-07-06', end_date: '2026-07-12', is_active: true },
    capacity_stats: { capacity: 20, enrolled: 11, remaining: 9, fill_pct: 55, is_at_capacity: false },
    application_stats: { total_submitted: 2, pending: 0, under_review: 0, approved: 2, rejected: 0, waitlisted: 0, cancelled: 0, acceptance_rate: 100 },
    recent_applications: [
      { id: 10, camper_name: 'James Foster', status: 'approved', submitted_at: '2026-01-29T09:00:00Z' },
      { id: 9, camper_name: 'Chloe Martin', status: 'approved', submitted_at: '2026-01-26T14:00:00Z' },
    ],
    age_distribution: { '7-9': 0, '10-12': 0, '13-15': 2, '16-17': 0 },
    gender_distribution: { male: 1, female: 1 },
  },
};

// ---------------------------------------------------------------------------
// Provider links
// ---------------------------------------------------------------------------

export const PROVIDER_LINKS = [
  {
    id: 1,
    camper_id: 1,
    camper: CAMPERS[0],
    token: 'demo-provider-token-abc123',
    expires_at: '2026-04-20T00:00:00Z',
    used_at: null,
    revoked_at: null,
    created_at: '2026-03-20T08:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Medical portal data
// ---------------------------------------------------------------------------

export const MEDICAL_INCIDENTS = [
  {
    id: 1,
    camper_id: 1,
    recorded_by: 9004,
    camper: { id: 1, full_name: 'Elijah Harmon' },
    // type matches IncidentType union; incident_type kept for any legacy references
    type: 'injury' as const,
    incident_type: 'fall',
    severity: 'minor' as const,
    title: 'Minor Knee Abrasion',
    description: 'Camper slipped on wet path near dining hall. Minor abrasion on left knee.',
    location: 'Dining Hall Path',
    escalation_required: false,
    // incident_date matches MedicalIncident.incident_date (date string); occurred_at kept as alias
    incident_date: '2025-07-10',
    occurred_at: '2025-07-10T14:30:00Z',
    created_at: '2025-07-10T15:00:00Z',
    updated_at: '2025-07-10T15:00:00Z',
  },
];

export const MEDICAL_FOLLOW_UPS = [
  {
    id: 1,
    camper_id: 5,
    created_by: 9004,
    camper: { id: 5, full_name: 'Ava Thompson' },
    // title matches MedicalFollowUp.title (required); description kept as alias
    title: 'Neurologist Clearance Required',
    description: 'Neurologist report required before final clearance.',
    status: 'submitted' as const,
    priority: 'high' as const,
    due_date: '2026-04-01',
    created_at: '2026-03-19T09:00:00Z',
    updated_at: '2026-03-19T09:00:00Z',
  },
];

export const MEDICAL_VISITS = [
  {
    id: 1,
    camper_id: 1,
    recorded_by: 9004,
    camper: { id: 1, full_name: 'Elijah Harmon' },
    // visit_date matches MedicalVisit.visit_date (date string); visited_at kept as alias
    visit_date: '2025-07-10',
    visited_at: '2025-07-10T15:00:00Z',
    // chief_complaint matches MedicalVisit.chief_complaint; complaint kept as alias
    chief_complaint: 'Knee abrasion following fall',
    complaint: 'Knee abrasion following fall',
    symptoms: 'Minor abrasion on left knee, no active bleeding.',
    assessment: 'Minor abrasion, cleaned and bandaged. No further intervention required.',
    disposition: 'returned_to_activity' as const,
    follow_up_required: false,
    created_at: '2025-07-10T15:10:00Z',
    updated_at: '2025-07-10T15:10:00Z',
  },
];

export const TREATMENT_LOGS = [
  {
    id: 1,
    camper_id: 1,
    medical_visit_id: null,
    recorded_by: 9004,
    recorder: { id: 9004, name: 'Dr. Demo Medical' },
    camper: { id: 1, full_name: 'Elijah Harmon' },
    treatment_date: '2025-07-10',
    treatment_time: '15:15',
    type: 'first_aid' as const,
    title: 'Knee abrasion treated',
    description: 'Cleaned and bandaged minor abrasion on left knee. No signs of infection.',
    outcome: 'Returned to activity after 15-minute rest.',
    medication_given: null,
    dosage_given: null,
    follow_up_required: false,
    follow_up_notes: null,
    created_at: '2025-07-10T15:15:00Z',
    updated_at: '2025-07-10T15:15:00Z',
  },
];

// ---------------------------------------------------------------------------
// Applicant portal data
// ---------------------------------------------------------------------------

export const APPLICANT_APPLICATIONS = APPLICATIONS.filter((a) => a.camper_id === 1);

export const APPLICANT_DOCUMENT_REQUESTS = DOCUMENT_REQUESTS.filter((d) => d.applicant_id === 201);

// ---------------------------------------------------------------------------
// Form schemas (for form builder)
// ---------------------------------------------------------------------------

export const FORM_DEFINITIONS = [
  {
    id: 1,
    title: 'Camp Application Form 2026',
    description: 'Standard application form for all Summer 2026 sessions.',
    version: 1,
    status: 'published',
    sections_count: 8,
    fields_count: 42,
    created_at: '2025-11-01T00:00:00Z',
    updated_at: '2026-01-15T00:00:00Z',
  },
];

// ---------------------------------------------------------------------------
// Notification preferences
// ---------------------------------------------------------------------------

export const NOTIFICATION_PREFERENCES = {
  application_updates: true,
  announcements: true,
  messages: true,
  deadlines: true,
};
